jboss/tyr

src/main/java/org/xstefank/check/TemplateChecker.java
Issue: https://github.com/xstefank/tyr/issues/17
=> [Issue #17] Allow to skip commit check with title defined

pom.xml, src/main/java/org/xstefank/check/RequiredRowsCheck.java, src/main/java/org/xstefank/check/SkipCheck.java, src/main/java/org/xstefank/check/TemplateChecker.java, src/main/java/org/xstefank/model/yaml/Format.java, src/test/java/org/xstefank/check/TitleCheckTest.java
Issue: https://github.com/xstefank/tyr/issues/14
=> [Issue #14] Add checkstyle plugin

pom.xml, src/test/java/org/xstefank/TestUtils.java, src/test/java/org/xstefank/YamlConfigTest.java, src/test/java/org/xstefank/api/GitHubAPITest.java, src/test/java/org/xstefank/check/RequiredRowsCheckTest.java, src/test/java/org/xstefank/check/TitleCheckTest.java, src/test/java/org/xstefank/check/additional/OneCommitOnlyCheckTest.java, src/test/java/org/xstefank/check/additional/TitleIssueLinkIncludedCheckTest.java, src/test/resources/json/badTestPayload.json, src/test/resources/json/testPayload.json, src/test/resources/testConfig.properties, src/test/resources/testPayload.json, src/test/resources/yaml/testTemplate.yaml
Issue: https://github.com/xstefank/tyr/issues/8
=> [Issue #8] Enhance testing and test coverage

src/main/java/org/xstefank/verification/FormatElementVerification.java, src/main/java/org/xstefank/verification/InvalidConfigurationException.java, src/main/java/org/xstefank/verification/RepositoryFormatVerification.java, src/main/java/org/xstefank/verification/Verification.java, src/main/java/org/xstefank/verification/VerificationHandler.java, src/main/java/org/xstefank/webhook/WebHookEndpoint.java, src/test/java/org/xstefank/verification/VerificationsTest.java, src/test/resources/yaml/wrongTemplate.yaml
Issue: https://github.com/xstefank/tyr/issues/26
=> [Issue #26] Implement control for the repository format in format.yaml

src/main/java/org/xstefank/webhook/WebHookEndpoint.java
Issue: https://github.com/xstefank/tyr/issues/31
=> [Issue #31] Format template is being loaded everytime when tyr is called by GitHub

src/main/java/org/xstefank/api/GitHubAPI.java, src/main/java/org/xstefank/model/TyrProperties.java, src/main/java/org/xstefank/model/Utils.java, src/test/java/org/xstefank/model/ConfigTest.java
Issue: https://github.com/xstefank/tyr/issues/35
=> [Issue #35] Properties should not be stored in Utils class

src/main/java/org/xstefank/check/LatestCommitCheck.java, src/main/java/org/xstefank/check/RequiredRowsCheck.java, src/main/java/org/xstefank/check/SkipCheck.java, src/main/java/org/xstefank/check/TemplateChecker.java, src/main/java/org/xstefank/check/TitleCheck.java, src/main/java/org/xstefank/model/yaml/Description.java, src/main/java/org/xstefank/model/yaml/Format.java, src/main/java/org/xstefank/model/yaml/RegexDefinition.java, src/main/resources/format.yaml, src/test/java/org/xstefank/TestUtils.java, src/test/java/org/xstefank/check/LatestCommitCheckTest.java, src/test/java/org/xstefank/check/RequiredRowsCheckTest.java, src/test/java/org/xstefank/check/SkipCheckTest.java, src/test/java/org/xstefank/check/TemplateCheckerTest.java, src/test/java/org/xstefank/check/TitleCheckTest.java, src/test/resources/json/testCommitsPayload.json, src/test/resources/yaml/testTemplate.yaml
=> [Issue #20] Make error messages for title and commit checks respectively configurable

src/test/java/org/xstefank/TestUtils.java, src/test/java/org/xstefank/model/ConfigTest.java
Issue: https://github.com/xstefank/tyr/issues/43
=> [Issue #43] Failing tests on Windows

pom.xml, src/main/java/org/xstefank/api/GitHubAPI.java, src/main/java/org/xstefank/model/Utils.java, src/test/java/org/xstefank/api/AuthenticationTestIT.java, src/test/java/org/xstefank/api/FakeGitHub.java, src/test/java/org/xstefank/api/GitHubAPITest.java, src/test/resources/arquillian.xml
Issue: https://github.com/xstefank/tyr/issues/42
=> [Issue #42] Add control and test for token authentication

src/main/java/org/xstefank/ci/ContinuousIntegration.java, src/main/java/org/xstefank/ci/TeamCityCI.java, src/main/java/org/xstefank/whitelist/CommandsLoader.java, src/main/java/org/xstefank/whitelist/RetestFailedCommand.java, src/main/java/org/xstefank/whitelist/WhitelistProcessing.java, src/main/resources/format.yaml, src/test/java/org/xstefank/ci/TestCI.java, src/test/java/org/xstefank/whitelist/RetestFailedCommandTest.java
Issue: https://github.com/xstefank/tyr/issues/39
=> [Issue #39] Add command for retesting only failed tests

src/main/java/org/xstefank/check/LatestCommitCheck.java, src/main/java/org/xstefank/check/SkipCheck.java, src/main/java/org/xstefank/model/Utils.java
Issue: https://github.com/xstefank/tyr/issues/54
=> [Issue #54] Verify that all strings returned from GitHub use \r\n

src/main/java/org/xstefank/api/GitHubAPI.java, src/main/java/org/xstefank/check/RequiredRowsCheck.java, src/main/java/org/xstefank/check/SkipCheck.java, src/main/java/org/xstefank/check/TemplateChecker.java, src/main/java/org/xstefank/check/additional/AdditionalChecks.java, src/main/java/org/xstefank/ci/CILoader.java, src/main/java/org/xstefank/ci/TeamCityCI.java, src/main/java/org/xstefank/model/PersistentList.java, src/main/java/org/xstefank/model/Utils.java, src/main/java/org/xstefank/model/yaml/Format.java, src/main/java/org/xstefank/verification/InvalidConfigurationException.java, src/main/java/org/xstefank/webhook/WebHookEndpoint.java, src/main/java/org/xstefank/whitelist/AddUserCommand.java, src/main/java/org/xstefank/whitelist/Command.java, src/main/java/org/xstefank/whitelist/RetestCommand.java, src/main/java/org/xstefank/whitelist/RetestFailedCommand.java, src/main/java/org/xstefank/whitelist/WhitelistProcessing.java, src/main/resources/format.yaml, src/test/java/org/xstefank/TestUtils.java, src/test/java/org/xstefank/check/LatestCommitCheckTest.java, src/test/java/org/xstefank/check/RequiredRowsCheckTest.java, src/test/java/org/xstefank/check/SkipCheckTest.java, src/test/java/org/xstefank/check/TemplateCheckerTest.java, src/test/java/org/xstefank/check/TitleCheckTest.java, src/test/java/org/xstefank/check/additional/OneCommitOnlyCheckTest.java, src/test/java/org/xstefank/check/additional/TitleIssueLinkIncludedCheckTest.java, src/test/java/org/xstefank/model/PersistentListTest.java, src/test/java/org/xstefank/whitelist/AddUserCommandTest.java, src/test/java/org/xstefank/whitelist/CommandTest.java, src/test/resources/yaml/testTemplate.yaml
Issue: https://github.com/xstefank/tyr/issues/32
=> [Issue #32] Code cleanup

src/main/java/org/xstefank/model/TyrProperties.java, src/main/java/org/xstefank/model/Utils.java, src/main/java/org/xstefank/webhook/WebHookEndpoint.java, src/main/java/org/xstefank/whitelist/WhitelistProcessing.java, src/test/java/org/xstefank/model/ConfigTest.java, src/test/java/org/xstefank/whitelist/CommandTest.java
Issue: https://github.com/xstefank/tyr/issues/38
=> [Issue #38] Remove JBOSS_CONFIG_DIR and make config directory configurable by system property

pom.xml, src/main/fabric8/deployment.yml
=> Issue #61 Add openshift configuration for Throntail runtime

src/main/resources/format.yaml
Issue: https://github.com/xstefank/tyr/issues/67
=> [Issue #67] Changing command regexes in format.yaml

src/main/java/org/xstefank/api/GitHubAPI.java, src/main/java/org/xstefank/check/Check.java, src/main/java/org/xstefank/check/LatestCommitCheck.java, src/main/java/org/xstefank/check/RequiredRowsCheck.java, src/main/java/org/xstefank/check/SkipCheck.java, src/main/java/org/xstefank/check/TemplateChecker.java, src/main/java/org/xstefank/check/TitleCheck.java, src/main/java/org/xstefank/check/additional/OneCommitOnlyCheck.java, src/main/java/org/xstefank/check/additional/TitleJIRAIssueLinkIncludedCheck.java, src/main/java/org/xstefank/ci/ContinuousIntegration.java, src/main/java/org/xstefank/ci/TeamCityCI.java, src/main/java/org/xstefank/model/json/BuildJson.java, src/main/java/org/xstefank/model/json/Properties.java, src/main/java/org/xstefank/model/json/Property.java, src/main/java/org/xstefank/webhook/WebHookEndpoint.java, src/main/java/org/xstefank/whitelist/AddUserCommand.java, src/main/java/org/xstefank/whitelist/Command.java, src/main/java/org/xstefank/whitelist/RetestCommand.java, src/main/java/org/xstefank/whitelist/RetestFailedCommand.java, src/main/java/org/xstefank/whitelist/WhitelistProcessing.java, src/main/resources/format-template.yaml, src/test/java/org/xstefank/TestUtils.java, src/test/java/org/xstefank/api/AuthenticationTestIT.java, src/test/java/org/xstefank/check/LatestCommitCheckTest.java, src/test/java/org/xstefank/check/SkipCheckTest.java, src/test/java/org/xstefank/ci/TestCI.java, src/test/java/org/xstefank/whitelist/CommandTest.java, src/test/resources/json/badTestPayload.json, src/test/resources/json/testPayload.json
Issue: https://github.com/xstefank/tyr/issues/47
=> [Issue #47] Replace fasterxml with JSON-B

src/main/java/org/xstefank/check/CommitMessagesCheck.java, src/main/java/org/xstefank/check/SkipCheck.java, src/main/java/org/xstefank/check/TemplateChecker.java, src/main/resources/format-template.yaml, src/test/java/org/xstefank/check/CommitMessagesCheckTest.java
Issue: https://github.com/xstefank/tyr/issues/65
=> [Issue #65] Check commit message of all commits in the pull request

pom.xml
resolves #72
https://github.com/jboss/tyr/issues/72
=> JsonObject is not by default deserialized by RESTEasy

tyr-runner/src/main/resources/format-template.yaml, tyr-runner/src/test/resources/yaml/testTemplate.yaml, tyr-runner/src/test/resources/yaml/wrongTemplate.yaml
Issue: https://github.com/jboss/tyr/issues/79
=> [Issue #79] Clear unused stuff from templates and examples

tyr-api/pom.xml, tyr-runner/pom.xml, tyr-runner/src/main/java/org/jboss/tyr/health/StatusHealthCheck.java, tyr-runner/src/test/java/org/jboss/tyr/api/AuthenticationTest.java, tyr-runner/src/test/java/org/jboss/tyr/api/GitHubAPITest.java
=> issue82 Base the project on Quarkus runtime

tyr-runner/pom.xml, tyr-runner/src/main/java/org/jboss/tyr/model/json/BuildJson.java, tyr-runner/src/main/java/org/jboss/tyr/model/json/BuildType.java, tyr-runner/src/main/java/org/jboss/tyr/model/json/Properties.java, tyr-runner/src/main/java/org/jboss/tyr/model/json/Property.java
=> issue84 Replace Jackson with JSON-B for client JAX-RS requests

tyr-runner/src/test/java/org/jboss/tyr/TestUtils.java, tyr-runner/src/test/resources/json/badTestPayload.json
Issue: https://github.com/jboss/tyr/issues/81
=> [Issue #81] One of the JSONs for tests is never used

tyr-runner/src/main/java/org/jboss/tyr/InvalidPayloadException.java, tyr-runner/src/main/java/org/jboss/tyr/ci/ContinuousIntegration.java, tyr-runner/src/main/java/org/jboss/tyr/ci/TeamCityCI.java, tyr-runner/src/main/java/org/jboss/tyr/model/json/SnapshotDependencies.java, tyr-runner/src/main/java/org/jboss/tyr/model/json/SnapshotDependency.java, tyr-runner/src/main/java/org/jboss/tyr/model/json/SnapshotDependencyProperties.java, tyr-runner/src/main/java/org/jboss/tyr/model/json/SourceBuildType.java, tyr-runner/src/main/java/org/jboss/tyr/whitelist/WhitelistProcessing.java, tyr-runner/src/test/java/org/jboss/tyr/TestUtils.java, tyr-runner/src/test/java/org/jboss/tyr/ci/TeamCityCITest.java, tyr-runner/src/test/resources/json/testPullRequestPayload.json
Issue: https://github.com/jboss/tyr/issues/57
=> [Issue #57] Implement Team City retest failed functionality

tyr-api/src/main/java/org/jboss/tyr/Check.java, tyr-api/src/main/java/org/jboss/tyr/Command.java, tyr-api/src/main/java/org/jboss/tyr/InvalidPayloadException.java, tyr-runner/src/main/java/org/jboss/tyr/api/GitHubAPI.java, tyr-runner/src/main/java/org/jboss/tyr/check/CommitMessagesCheck.java, tyr-runner/src/main/java/org/jboss/tyr/check/SkipCheck.java, tyr-runner/src/main/java/org/jboss/tyr/check/TemplateChecker.java, tyr-runner/src/main/java/org/jboss/tyr/ci/TeamCityCI.java, tyr-runner/src/main/java/org/jboss/tyr/webhook/WebHookEndpoint.java, tyr-runner/src/main/java/org/jboss/tyr/whitelist/AddUserCommand.java, tyr-runner/src/main/java/org/jboss/tyr/whitelist/RetestCommand.java, tyr-runner/src/main/java/org/jboss/tyr/whitelist/RetestFailedCommand.java, tyr-runner/src/main/java/org/jboss/tyr/whitelist/WhitelistProcessing.java, tyr-runner/src/test/java/org/jboss/tyr/additional/AdditionalResourcesTest.java, tyr-runner/src/test/java/org/jboss/tyr/api/GitHubAPITest.java, tyr-runner/src/test/java/org/jboss/tyr/check/CommitMessagesCheckTest.java, tyr-runner/src/test/java/org/jboss/tyr/check/SkipCheckTest.java, tyr-runner/src/test/java/org/jboss/tyr/model/ConfigTest.java, tyr-runner/src/test/java/org/jboss/tyr/whitelist/AddUserCommandTest.java, tyr-runner/src/test/java/org/jboss/tyr/whitelist/RetestCommandTest.java, tyr-runner/src/test/java/org/jboss/tyr/whitelist/RetestFailedCommandTest.java
Issue: https://github.com/jboss/tyr/issues/97
=> [Issue #97] Add usage of InvalidPayloadException

tyr-runner/pom.xml
And all other required dependencies.
=> Update quarkus to 1.3.0.Final

tyr-runner/.mvn/wrapper/MavenWrapperDownloader.java, tyr-runner/.mvn/wrapper/maven-wrapper.properties, tyr-runner/mvnw, tyr-runner/mvnw.cmd
Since it is a quarkus project now.
=> Add mvnw to tyr-runner

.github/workflows/ci.yml, .travis.yml, README.md
=> Move CI to GitHub actions

tyr-runner/pom.xml, tyr-runner/src/main/java/org/jboss/tyr/whitelist/TestBean.java, tyr-runner/src/test/java/org/jboss/tyr/additional/AdditionalResourcesTest.java, tyr-runner/src/test/java/org/jboss/tyr/api/AuthenticationTest.java, tyr-runner/src/test/java/org/jboss/tyr/api/GitHubAPITest.java, tyr-runner/src/test/java/org/jboss/tyr/check/CommitMessagesCheckTest.java, tyr-runner/src/test/java/org/jboss/tyr/check/RequiredRowsCheckTest.java, tyr-runner/src/test/java/org/jboss/tyr/check/SkipCheckTest.java, tyr-runner/src/test/java/org/jboss/tyr/check/TemplateCheckerTest.java, tyr-runner/src/test/java/org/jboss/tyr/check/TitleCheckTest.java, tyr-runner/src/test/java/org/jboss/tyr/ci/TeamCityCITest.java, tyr-runner/src/test/java/org/jboss/tyr/command/AddUserCommandTest.java, tyr-runner/src/test/java/org/jboss/tyr/command/CommandTest.java, tyr-runner/src/test/java/org/jboss/tyr/command/RetestCommandTest.java, tyr-runner/src/test/java/org/jboss/tyr/command/RetestFailedCommandTest.java, tyr-runner/src/test/java/org/jboss/tyr/model/ConfigTest.java, tyr-runner/src/test/java/org/jboss/tyr/model/PersistentListTest.java, tyr-runner/src/test/java/org/jboss/tyr/verification/VerificationsTest.java
=> Update to JUnit 5

pom.xml, tyr-api/pom.xml, webhook/pom.xml, webhook/src/main/java/org/jboss/tyr/Webhook.java
=> Add webhook service

tyr-runner/src/test/java/org/jboss/tyr/check/TemplateCheckerTest.java
=> Add test for valid PR check

tyr-api/pom.xml
=> [issue #99] Get rid of encoding warning

tyr-cli/src/main/java/org/jboss/tyr/cli/TyrMain.java, tyr-core/src/main/java/org/jboss/tyr/check/TemplateChecker.java
=> [#158] tyr-cli doesn't process whitelisting

tyr-cli/src/main/java/org/jboss/tyr/cli/TyrMain.java, tyr-cli/src/main/resources/application.properties
=> Remove Quarkus output from the tyr-cli

tyr-cli/src/main/resources/reflection-config.json
=> Add StatusPayload to the reflection-config.json

.github/workflows/ci.yml, pom.xml, tyr-api/pom.xml, tyr-cli/pom.xml, tyr-core/pom.xml, tyr-core/src/main/java/org/jboss/tyr/check/TemplateChecker.java, tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java, tyr-core/src/test/java/org/jboss/tyr/config/pushstatus/PushStatusFalseTestProfile.java, tyr-core/src/test/java/org/jboss/tyr/config/pushstatus/TemplateCheckPushStatusTest.java, tyr-core/src/test/resources/application.properties, tyr-core/src/test/resources/json/testPayload.json, tyr-webhook/pom.xml
Fixes #174 
This also updates the project to JDK 11.
=> Add a config option to skip the PR status push

tyr-cli/src/main/resources/application.properties, tyr-core/src/main/java/org/jboss/tyr/check/TemplateChecker.java
=> Add a log message when the template check is skipped

tyr-core/src/main/java/org/jboss/tyr/model/AdditionalResourcesLoader.java
=> Fix typo in AdditionalResourcesLoader

README.md, tyr-core/src/main/java/org/jboss/tyr/check/SkipCheck.java, tyr-core/src/main/java/org/jboss/tyr/check/TemplateChecker.java, tyr-core/src/main/java/org/jboss/tyr/config/TyrConfiguration.java, tyr-core/src/main/java/org/jboss/tyr/github/GitHubService.java, tyr-core/src/main/resources/format-example-without-commits.yaml
Added switch for the limited Tyr functionality on private repos with unchanged scope of oauth token permissions.
Readme updated.
Resolves #157
=> Switch for limited Tyr functionality on private repos.

.github/tyr-format.yaml, .github/workflows/tyr-check.yml
=> Add tyr GH action

tyr-core/src/main/java/org/jboss/tyr/ci/TeamCity.java, tyr-core/src/main/java/org/jboss/tyr/github/GitHubService.java
Fixes https://github.com/jboss/tyr/issues/192
=> Fixed close client warning.

tyr-core/src/main/java/org/jboss/tyr/model/Utils.java, tyr-core/src/main/java/org/jboss/tyr/verification/RepositoryFormatVerification.java, tyr-core/src/test/java/org/jboss/tyr/verification/VerificationsTest.java
=> [Issue #200]Fixes regex that verifies repository format

.github/tyr-format.yaml
=> [Issue #194]Added case-insensitive modifier to tyr-format.yaml regex.

.github/workflows/ci.yml
=> Update ci action target branch to main
